#!/bin/bash

if [ $# != 1 ]; then
    echo "error"
    exit 1
fi

for ((i=0;i<600;i++));
do
    ping -c 1 -W 1 $1 &> /dev/null
    error=$?
    if [ $error == 0 ]; then
        break
    fi
    let "mod = $i % 5"
    if [ "$mod" == "0" ]; then
        echo "$1 not responding... trying again"
    fi
    sleep 1
done
echo "$1 is awake"
notify-send --urgency=low "$1 is awake" 
